# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/troyd/Projects/vis_interpreter_dart/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/troyd/Projects/vis_interpreter_dart/src

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	cd /home/troyd/Projects/vis_interpreter_dart/src && $(CMAKE_COMMAND) -E cmake_progress_start /home/troyd/Projects/vis_interpreter_dart/src/CMakeFiles /home/troyd/Projects/vis_interpreter_dart/src/lib/VIS-Interpreter/CMakeFiles/progress.marks
	cd /home/troyd/Projects/vis_interpreter_dart/src && $(MAKE) -f CMakeFiles/Makefile2 lib/VIS-Interpreter/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/troyd/Projects/vis_interpreter_dart/src/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/troyd/Projects/vis_interpreter_dart/src && $(MAKE) -f CMakeFiles/Makefile2 lib/VIS-Interpreter/clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/troyd/Projects/vis_interpreter_dart/src && $(MAKE) -f CMakeFiles/Makefile2 lib/VIS-Interpreter/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/troyd/Projects/vis_interpreter_dart/src && $(MAKE) -f CMakeFiles/Makefile2 lib/VIS-Interpreter/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/troyd/Projects/vis_interpreter_dart/src && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
lib/VIS-Interpreter/CMakeFiles/vis-tester.dir/rule:
	cd /home/troyd/Projects/vis_interpreter_dart/src && $(MAKE) -f CMakeFiles/Makefile2 lib/VIS-Interpreter/CMakeFiles/vis-tester.dir/rule
.PHONY : lib/VIS-Interpreter/CMakeFiles/vis-tester.dir/rule

# Convenience name for target.
vis-tester: lib/VIS-Interpreter/CMakeFiles/vis-tester.dir/rule

.PHONY : vis-tester

# fast build rule for target.
vis-tester/fast:
	cd /home/troyd/Projects/vis_interpreter_dart/src && $(MAKE) -f lib/VIS-Interpreter/CMakeFiles/vis-tester.dir/build.make lib/VIS-Interpreter/CMakeFiles/vis-tester.dir/build
.PHONY : vis-tester/fast

# Convenience name for target.
lib/VIS-Interpreter/CMakeFiles/VISL.dir/rule:
	cd /home/troyd/Projects/vis_interpreter_dart/src && $(MAKE) -f CMakeFiles/Makefile2 lib/VIS-Interpreter/CMakeFiles/VISL.dir/rule
.PHONY : lib/VIS-Interpreter/CMakeFiles/VISL.dir/rule

# Convenience name for target.
VISL: lib/VIS-Interpreter/CMakeFiles/VISL.dir/rule

.PHONY : VISL

# fast build rule for target.
VISL/fast:
	cd /home/troyd/Projects/vis_interpreter_dart/src && $(MAKE) -f lib/VIS-Interpreter/CMakeFiles/VISL.dir/build.make lib/VIS-Interpreter/CMakeFiles/VISL.dir/build
.PHONY : VISL/fast

src/VIS-Interpreter.o: src/VIS-Interpreter.cpp.o

.PHONY : src/VIS-Interpreter.o

# target to build an object file
src/VIS-Interpreter.cpp.o:
	cd /home/troyd/Projects/vis_interpreter_dart/src && $(MAKE) -f lib/VIS-Interpreter/CMakeFiles/vis-tester.dir/build.make lib/VIS-Interpreter/CMakeFiles/vis-tester.dir/src/VIS-Interpreter.cpp.o
	cd /home/troyd/Projects/vis_interpreter_dart/src && $(MAKE) -f lib/VIS-Interpreter/CMakeFiles/VISL.dir/build.make lib/VIS-Interpreter/CMakeFiles/VISL.dir/src/VIS-Interpreter.cpp.o
.PHONY : src/VIS-Interpreter.cpp.o

src/VIS-Interpreter.i: src/VIS-Interpreter.cpp.i

.PHONY : src/VIS-Interpreter.i

# target to preprocess a source file
src/VIS-Interpreter.cpp.i:
	cd /home/troyd/Projects/vis_interpreter_dart/src && $(MAKE) -f lib/VIS-Interpreter/CMakeFiles/vis-tester.dir/build.make lib/VIS-Interpreter/CMakeFiles/vis-tester.dir/src/VIS-Interpreter.cpp.i
	cd /home/troyd/Projects/vis_interpreter_dart/src && $(MAKE) -f lib/VIS-Interpreter/CMakeFiles/VISL.dir/build.make lib/VIS-Interpreter/CMakeFiles/VISL.dir/src/VIS-Interpreter.cpp.i
.PHONY : src/VIS-Interpreter.cpp.i

src/VIS-Interpreter.s: src/VIS-Interpreter.cpp.s

.PHONY : src/VIS-Interpreter.s

# target to generate assembly for a file
src/VIS-Interpreter.cpp.s:
	cd /home/troyd/Projects/vis_interpreter_dart/src && $(MAKE) -f lib/VIS-Interpreter/CMakeFiles/vis-tester.dir/build.make lib/VIS-Interpreter/CMakeFiles/vis-tester.dir/src/VIS-Interpreter.cpp.s
	cd /home/troyd/Projects/vis_interpreter_dart/src && $(MAKE) -f lib/VIS-Interpreter/CMakeFiles/VISL.dir/build.make lib/VIS-Interpreter/CMakeFiles/VISL.dir/src/VIS-Interpreter.cpp.s
.PHONY : src/VIS-Interpreter.cpp.s

src/VISCWrapper.o: src/VISCWrapper.cpp.o

.PHONY : src/VISCWrapper.o

# target to build an object file
src/VISCWrapper.cpp.o:
	cd /home/troyd/Projects/vis_interpreter_dart/src && $(MAKE) -f lib/VIS-Interpreter/CMakeFiles/vis-tester.dir/build.make lib/VIS-Interpreter/CMakeFiles/vis-tester.dir/src/VISCWrapper.cpp.o
	cd /home/troyd/Projects/vis_interpreter_dart/src && $(MAKE) -f lib/VIS-Interpreter/CMakeFiles/VISL.dir/build.make lib/VIS-Interpreter/CMakeFiles/VISL.dir/src/VISCWrapper.cpp.o
.PHONY : src/VISCWrapper.cpp.o

src/VISCWrapper.i: src/VISCWrapper.cpp.i

.PHONY : src/VISCWrapper.i

# target to preprocess a source file
src/VISCWrapper.cpp.i:
	cd /home/troyd/Projects/vis_interpreter_dart/src && $(MAKE) -f lib/VIS-Interpreter/CMakeFiles/vis-tester.dir/build.make lib/VIS-Interpreter/CMakeFiles/vis-tester.dir/src/VISCWrapper.cpp.i
	cd /home/troyd/Projects/vis_interpreter_dart/src && $(MAKE) -f lib/VIS-Interpreter/CMakeFiles/VISL.dir/build.make lib/VIS-Interpreter/CMakeFiles/VISL.dir/src/VISCWrapper.cpp.i
.PHONY : src/VISCWrapper.cpp.i

src/VISCWrapper.s: src/VISCWrapper.cpp.s

.PHONY : src/VISCWrapper.s

# target to generate assembly for a file
src/VISCWrapper.cpp.s:
	cd /home/troyd/Projects/vis_interpreter_dart/src && $(MAKE) -f lib/VIS-Interpreter/CMakeFiles/vis-tester.dir/build.make lib/VIS-Interpreter/CMakeFiles/vis-tester.dir/src/VISCWrapper.cpp.s
	cd /home/troyd/Projects/vis_interpreter_dart/src && $(MAKE) -f lib/VIS-Interpreter/CMakeFiles/VISL.dir/build.make lib/VIS-Interpreter/CMakeFiles/VISL.dir/src/VISCWrapper.cpp.s
.PHONY : src/VISCWrapper.cpp.s

src/VISFile.o: src/VISFile.cpp.o

.PHONY : src/VISFile.o

# target to build an object file
src/VISFile.cpp.o:
	cd /home/troyd/Projects/vis_interpreter_dart/src && $(MAKE) -f lib/VIS-Interpreter/CMakeFiles/vis-tester.dir/build.make lib/VIS-Interpreter/CMakeFiles/vis-tester.dir/src/VISFile.cpp.o
	cd /home/troyd/Projects/vis_interpreter_dart/src && $(MAKE) -f lib/VIS-Interpreter/CMakeFiles/VISL.dir/build.make lib/VIS-Interpreter/CMakeFiles/VISL.dir/src/VISFile.cpp.o
.PHONY : src/VISFile.cpp.o

src/VISFile.i: src/VISFile.cpp.i

.PHONY : src/VISFile.i

# target to preprocess a source file
src/VISFile.cpp.i:
	cd /home/troyd/Projects/vis_interpreter_dart/src && $(MAKE) -f lib/VIS-Interpreter/CMakeFiles/vis-tester.dir/build.make lib/VIS-Interpreter/CMakeFiles/vis-tester.dir/src/VISFile.cpp.i
	cd /home/troyd/Projects/vis_interpreter_dart/src && $(MAKE) -f lib/VIS-Interpreter/CMakeFiles/VISL.dir/build.make lib/VIS-Interpreter/CMakeFiles/VISL.dir/src/VISFile.cpp.i
.PHONY : src/VISFile.cpp.i

src/VISFile.s: src/VISFile.cpp.s

.PHONY : src/VISFile.s

# target to generate assembly for a file
src/VISFile.cpp.s:
	cd /home/troyd/Projects/vis_interpreter_dart/src && $(MAKE) -f lib/VIS-Interpreter/CMakeFiles/vis-tester.dir/build.make lib/VIS-Interpreter/CMakeFiles/vis-tester.dir/src/VISFile.cpp.s
	cd /home/troyd/Projects/vis_interpreter_dart/src && $(MAKE) -f lib/VIS-Interpreter/CMakeFiles/VISL.dir/build.make lib/VIS-Interpreter/CMakeFiles/VISL.dir/src/VISFile.cpp.s
.PHONY : src/VISFile.cpp.s

src/VISParser.o: src/VISParser.cpp.o

.PHONY : src/VISParser.o

# target to build an object file
src/VISParser.cpp.o:
	cd /home/troyd/Projects/vis_interpreter_dart/src && $(MAKE) -f lib/VIS-Interpreter/CMakeFiles/vis-tester.dir/build.make lib/VIS-Interpreter/CMakeFiles/vis-tester.dir/src/VISParser.cpp.o
	cd /home/troyd/Projects/vis_interpreter_dart/src && $(MAKE) -f lib/VIS-Interpreter/CMakeFiles/VISL.dir/build.make lib/VIS-Interpreter/CMakeFiles/VISL.dir/src/VISParser.cpp.o
.PHONY : src/VISParser.cpp.o

src/VISParser.i: src/VISParser.cpp.i

.PHONY : src/VISParser.i

# target to preprocess a source file
src/VISParser.cpp.i:
	cd /home/troyd/Projects/vis_interpreter_dart/src && $(MAKE) -f lib/VIS-Interpreter/CMakeFiles/vis-tester.dir/build.make lib/VIS-Interpreter/CMakeFiles/vis-tester.dir/src/VISParser.cpp.i
	cd /home/troyd/Projects/vis_interpreter_dart/src && $(MAKE) -f lib/VIS-Interpreter/CMakeFiles/VISL.dir/build.make lib/VIS-Interpreter/CMakeFiles/VISL.dir/src/VISParser.cpp.i
.PHONY : src/VISParser.cpp.i

src/VISParser.s: src/VISParser.cpp.s

.PHONY : src/VISParser.s

# target to generate assembly for a file
src/VISParser.cpp.s:
	cd /home/troyd/Projects/vis_interpreter_dart/src && $(MAKE) -f lib/VIS-Interpreter/CMakeFiles/vis-tester.dir/build.make lib/VIS-Interpreter/CMakeFiles/vis-tester.dir/src/VISParser.cpp.s
	cd /home/troyd/Projects/vis_interpreter_dart/src && $(MAKE) -f lib/VIS-Interpreter/CMakeFiles/VISL.dir/build.make lib/VIS-Interpreter/CMakeFiles/VISL.dir/src/VISParser.cpp.s
.PHONY : src/VISParser.cpp.s

src/VISTypes.o: src/VISTypes.cpp.o

.PHONY : src/VISTypes.o

# target to build an object file
src/VISTypes.cpp.o:
	cd /home/troyd/Projects/vis_interpreter_dart/src && $(MAKE) -f lib/VIS-Interpreter/CMakeFiles/vis-tester.dir/build.make lib/VIS-Interpreter/CMakeFiles/vis-tester.dir/src/VISTypes.cpp.o
	cd /home/troyd/Projects/vis_interpreter_dart/src && $(MAKE) -f lib/VIS-Interpreter/CMakeFiles/VISL.dir/build.make lib/VIS-Interpreter/CMakeFiles/VISL.dir/src/VISTypes.cpp.o
.PHONY : src/VISTypes.cpp.o

src/VISTypes.i: src/VISTypes.cpp.i

.PHONY : src/VISTypes.i

# target to preprocess a source file
src/VISTypes.cpp.i:
	cd /home/troyd/Projects/vis_interpreter_dart/src && $(MAKE) -f lib/VIS-Interpreter/CMakeFiles/vis-tester.dir/build.make lib/VIS-Interpreter/CMakeFiles/vis-tester.dir/src/VISTypes.cpp.i
	cd /home/troyd/Projects/vis_interpreter_dart/src && $(MAKE) -f lib/VIS-Interpreter/CMakeFiles/VISL.dir/build.make lib/VIS-Interpreter/CMakeFiles/VISL.dir/src/VISTypes.cpp.i
.PHONY : src/VISTypes.cpp.i

src/VISTypes.s: src/VISTypes.cpp.s

.PHONY : src/VISTypes.s

# target to generate assembly for a file
src/VISTypes.cpp.s:
	cd /home/troyd/Projects/vis_interpreter_dart/src && $(MAKE) -f lib/VIS-Interpreter/CMakeFiles/vis-tester.dir/build.make lib/VIS-Interpreter/CMakeFiles/vis-tester.dir/src/VISTypes.cpp.s
	cd /home/troyd/Projects/vis_interpreter_dart/src && $(MAKE) -f lib/VIS-Interpreter/CMakeFiles/VISL.dir/build.make lib/VIS-Interpreter/CMakeFiles/VISL.dir/src/VISTypes.cpp.s
.PHONY : src/VISTypes.cpp.s

src/VISUtils.o: src/VISUtils.cpp.o

.PHONY : src/VISUtils.o

# target to build an object file
src/VISUtils.cpp.o:
	cd /home/troyd/Projects/vis_interpreter_dart/src && $(MAKE) -f lib/VIS-Interpreter/CMakeFiles/vis-tester.dir/build.make lib/VIS-Interpreter/CMakeFiles/vis-tester.dir/src/VISUtils.cpp.o
	cd /home/troyd/Projects/vis_interpreter_dart/src && $(MAKE) -f lib/VIS-Interpreter/CMakeFiles/VISL.dir/build.make lib/VIS-Interpreter/CMakeFiles/VISL.dir/src/VISUtils.cpp.o
.PHONY : src/VISUtils.cpp.o

src/VISUtils.i: src/VISUtils.cpp.i

.PHONY : src/VISUtils.i

# target to preprocess a source file
src/VISUtils.cpp.i:
	cd /home/troyd/Projects/vis_interpreter_dart/src && $(MAKE) -f lib/VIS-Interpreter/CMakeFiles/vis-tester.dir/build.make lib/VIS-Interpreter/CMakeFiles/vis-tester.dir/src/VISUtils.cpp.i
	cd /home/troyd/Projects/vis_interpreter_dart/src && $(MAKE) -f lib/VIS-Interpreter/CMakeFiles/VISL.dir/build.make lib/VIS-Interpreter/CMakeFiles/VISL.dir/src/VISUtils.cpp.i
.PHONY : src/VISUtils.cpp.i

src/VISUtils.s: src/VISUtils.cpp.s

.PHONY : src/VISUtils.s

# target to generate assembly for a file
src/VISUtils.cpp.s:
	cd /home/troyd/Projects/vis_interpreter_dart/src && $(MAKE) -f lib/VIS-Interpreter/CMakeFiles/vis-tester.dir/build.make lib/VIS-Interpreter/CMakeFiles/vis-tester.dir/src/VISUtils.cpp.s
	cd /home/troyd/Projects/vis_interpreter_dart/src && $(MAKE) -f lib/VIS-Interpreter/CMakeFiles/VISL.dir/build.make lib/VIS-Interpreter/CMakeFiles/VISL.dir/src/VISUtils.cpp.s
.PHONY : src/VISUtils.cpp.s

src/test/main.o: src/test/main.cpp.o

.PHONY : src/test/main.o

# target to build an object file
src/test/main.cpp.o:
	cd /home/troyd/Projects/vis_interpreter_dart/src && $(MAKE) -f lib/VIS-Interpreter/CMakeFiles/vis-tester.dir/build.make lib/VIS-Interpreter/CMakeFiles/vis-tester.dir/src/test/main.cpp.o
	cd /home/troyd/Projects/vis_interpreter_dart/src && $(MAKE) -f lib/VIS-Interpreter/CMakeFiles/VISL.dir/build.make lib/VIS-Interpreter/CMakeFiles/VISL.dir/src/test/main.cpp.o
.PHONY : src/test/main.cpp.o

src/test/main.i: src/test/main.cpp.i

.PHONY : src/test/main.i

# target to preprocess a source file
src/test/main.cpp.i:
	cd /home/troyd/Projects/vis_interpreter_dart/src && $(MAKE) -f lib/VIS-Interpreter/CMakeFiles/vis-tester.dir/build.make lib/VIS-Interpreter/CMakeFiles/vis-tester.dir/src/test/main.cpp.i
	cd /home/troyd/Projects/vis_interpreter_dart/src && $(MAKE) -f lib/VIS-Interpreter/CMakeFiles/VISL.dir/build.make lib/VIS-Interpreter/CMakeFiles/VISL.dir/src/test/main.cpp.i
.PHONY : src/test/main.cpp.i

src/test/main.s: src/test/main.cpp.s

.PHONY : src/test/main.s

# target to generate assembly for a file
src/test/main.cpp.s:
	cd /home/troyd/Projects/vis_interpreter_dart/src && $(MAKE) -f lib/VIS-Interpreter/CMakeFiles/vis-tester.dir/build.make lib/VIS-Interpreter/CMakeFiles/vis-tester.dir/src/test/main.cpp.s
	cd /home/troyd/Projects/vis_interpreter_dart/src && $(MAKE) -f lib/VIS-Interpreter/CMakeFiles/VISL.dir/build.make lib/VIS-Interpreter/CMakeFiles/VISL.dir/src/test/main.cpp.s
.PHONY : src/test/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... vis-tester"
	@echo "... VISL"
	@echo "... src/VIS-Interpreter.o"
	@echo "... src/VIS-Interpreter.i"
	@echo "... src/VIS-Interpreter.s"
	@echo "... src/VISCWrapper.o"
	@echo "... src/VISCWrapper.i"
	@echo "... src/VISCWrapper.s"
	@echo "... src/VISFile.o"
	@echo "... src/VISFile.i"
	@echo "... src/VISFile.s"
	@echo "... src/VISParser.o"
	@echo "... src/VISParser.i"
	@echo "... src/VISParser.s"
	@echo "... src/VISTypes.o"
	@echo "... src/VISTypes.i"
	@echo "... src/VISTypes.s"
	@echo "... src/VISUtils.o"
	@echo "... src/VISUtils.i"
	@echo "... src/VISUtils.s"
	@echo "... src/test/main.o"
	@echo "... src/test/main.i"
	@echo "... src/test/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/troyd/Projects/vis_interpreter_dart/src && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

