# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/troyd/Projects/VIS-Interpreter

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/troyd/Projects/VIS-Interpreter

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/troyd/Projects/VIS-Interpreter/CMakeFiles /home/troyd/Projects/VIS-Interpreter/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/troyd/Projects/VIS-Interpreter/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named visl-test

# Build rule for target.
visl-test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 visl-test
.PHONY : visl-test

# fast build rule for target.
visl-test/fast:
	$(MAKE) -f CMakeFiles/visl-test.dir/build.make CMakeFiles/visl-test.dir/build
.PHONY : visl-test/fast

#=============================================================================
# Target rules for targets named VISL

# Build rule for target.
VISL: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 VISL
.PHONY : VISL

# fast build rule for target.
VISL/fast:
	$(MAKE) -f CMakeFiles/VISL.dir/build.make CMakeFiles/VISL.dir/build
.PHONY : VISL/fast

src/VISCommands.o: src/VISCommands.cpp.o

.PHONY : src/VISCommands.o

# target to build an object file
src/VISCommands.cpp.o:
	$(MAKE) -f CMakeFiles/VISL.dir/build.make CMakeFiles/VISL.dir/src/VISCommands.cpp.o
.PHONY : src/VISCommands.cpp.o

src/VISCommands.i: src/VISCommands.cpp.i

.PHONY : src/VISCommands.i

# target to preprocess a source file
src/VISCommands.cpp.i:
	$(MAKE) -f CMakeFiles/VISL.dir/build.make CMakeFiles/VISL.dir/src/VISCommands.cpp.i
.PHONY : src/VISCommands.cpp.i

src/VISCommands.s: src/VISCommands.cpp.s

.PHONY : src/VISCommands.s

# target to generate assembly for a file
src/VISCommands.cpp.s:
	$(MAKE) -f CMakeFiles/VISL.dir/build.make CMakeFiles/VISL.dir/src/VISCommands.cpp.s
.PHONY : src/VISCommands.cpp.s

src/VISInterpreter.o: src/VISInterpreter.cpp.o

.PHONY : src/VISInterpreter.o

# target to build an object file
src/VISInterpreter.cpp.o:
	$(MAKE) -f CMakeFiles/VISL.dir/build.make CMakeFiles/VISL.dir/src/VISInterpreter.cpp.o
.PHONY : src/VISInterpreter.cpp.o

src/VISInterpreter.i: src/VISInterpreter.cpp.i

.PHONY : src/VISInterpreter.i

# target to preprocess a source file
src/VISInterpreter.cpp.i:
	$(MAKE) -f CMakeFiles/VISL.dir/build.make CMakeFiles/VISL.dir/src/VISInterpreter.cpp.i
.PHONY : src/VISInterpreter.cpp.i

src/VISInterpreter.s: src/VISInterpreter.cpp.s

.PHONY : src/VISInterpreter.s

# target to generate assembly for a file
src/VISInterpreter.cpp.s:
	$(MAKE) -f CMakeFiles/VISL.dir/build.make CMakeFiles/VISL.dir/src/VISInterpreter.cpp.s
.PHONY : src/VISInterpreter.cpp.s

src/VISLexer.o: src/VISLexer.cpp.o

.PHONY : src/VISLexer.o

# target to build an object file
src/VISLexer.cpp.o:
	$(MAKE) -f CMakeFiles/VISL.dir/build.make CMakeFiles/VISL.dir/src/VISLexer.cpp.o
.PHONY : src/VISLexer.cpp.o

src/VISLexer.i: src/VISLexer.cpp.i

.PHONY : src/VISLexer.i

# target to preprocess a source file
src/VISLexer.cpp.i:
	$(MAKE) -f CMakeFiles/VISL.dir/build.make CMakeFiles/VISL.dir/src/VISLexer.cpp.i
.PHONY : src/VISLexer.cpp.i

src/VISLexer.s: src/VISLexer.cpp.s

.PHONY : src/VISLexer.s

# target to generate assembly for a file
src/VISLexer.cpp.s:
	$(MAKE) -f CMakeFiles/VISL.dir/build.make CMakeFiles/VISL.dir/src/VISLexer.cpp.s
.PHONY : src/VISLexer.cpp.s

test/main.o: test/main.cpp.o

.PHONY : test/main.o

# target to build an object file
test/main.cpp.o:
	$(MAKE) -f CMakeFiles/visl-test.dir/build.make CMakeFiles/visl-test.dir/test/main.cpp.o
.PHONY : test/main.cpp.o

test/main.i: test/main.cpp.i

.PHONY : test/main.i

# target to preprocess a source file
test/main.cpp.i:
	$(MAKE) -f CMakeFiles/visl-test.dir/build.make CMakeFiles/visl-test.dir/test/main.cpp.i
.PHONY : test/main.cpp.i

test/main.s: test/main.cpp.s

.PHONY : test/main.s

# target to generate assembly for a file
test/main.cpp.s:
	$(MAKE) -f CMakeFiles/visl-test.dir/build.make CMakeFiles/visl-test.dir/test/main.cpp.s
.PHONY : test/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... visl-test"
	@echo "... VISL"
	@echo "... src/VISCommands.o"
	@echo "... src/VISCommands.i"
	@echo "... src/VISCommands.s"
	@echo "... src/VISInterpreter.o"
	@echo "... src/VISInterpreter.i"
	@echo "... src/VISInterpreter.s"
	@echo "... src/VISLexer.o"
	@echo "... src/VISLexer.i"
	@echo "... src/VISLexer.s"
	@echo "... test/main.o"
	@echo "... test/main.i"
	@echo "... test/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

